-- 91	Retrieve the details of the most expensive rental made by customer ID 100.
-- 92	Get the titles of all films with a replacement cost of exactly $20.
-- 93	Find the customers who have rented films with a rating of 'NC-17'.